---
- name: install docker on rhel7.7 host
  hosts: dockerhost

  tasks:
    - name: is this registered RHEL host
      redhat-subscription:
        state: present
        username: ""
        password: ""

