---
- name: install docker on rhel7.7 host
  hosts: dockerhost
  become: true

  tasks:
  # install this collection from galaxy : ansible-galaxy collection install community.general
    - name: is this registered RHEL host
      community.general.redhat_subscription:
        state: present
        username: ""
        password: ""
      when: 
        - ansible_facts['distribution'] == "RedHat"

    - name: Print the ansible_fact
      ansible.builtin.debug:
        msg: "{{ ansible_facts['distribution'] }}"
      #when: ansible_default_ipv4.gateway is defined

    - name: enable rhel repositories
      community.general.rhsm_repository:
        name: "{{ item }}"
        state: enabled
      loop: 
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    - name: install repository- EPEL
      yum:
        name: epel-release
        state: installed      

    - name: install docker
      yum:
        name: docker
        state: latest
      
    - name: start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install a list of packages (suitable replacement for 2.11 loop deprecation warning)
      yum:
        name:
          - git
        state: present

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/pachumon/ansible-docker.git'
        dest: /home/azureuser/ansible-docker
         