---
- name: install docker on rhel8 host
  hosts: dockerhost

  tasks:
    - name: Create Yum Repo
      yum_repository:
        name: "docker"
        description: "this is a docker repo"
        reposdir: "/etc/yum.repos.d/"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        gpgcheck : "no"
        enabled: yes

    - name: run yum repolist
      command: yum repolist
    
    - name: run docker cmd
      command: yum install -y --nobest docker-ce

    - name: Check Package
      package:
        name: "docker-ce"
        state: present

#    - name: install docker
#      yum:
#        name: docker-ce
#        state: latest

    - name: start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes
