---
- name: install docker on rhel7.7 host
  hosts: dockerhost

  tasks:
  # install this collection from galaxy : ansible-galaxy collection install community.general
    - name: is this registered RHEL host
      community.general.redhat_subscription:
        state: present
        username: ""
        password: ""
      when: 
        - ansible_facts['distribution'] == "RedHat"

    - name: enable rhel repositories
      community.general.rhsm_repository:
        name: "{{ item }}"
        state: enabled
      loop: 
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7.7"
        