---
- name: create container image
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:

    - name: Log into DockerHub
      community.docker.docker_login:
        username: ""
        password: ""
      register: login

    - name: show login information
      debug:
        var: login

    - name: create an image from the docker file in current directory
      docker_image:
        name: docker.io/pachumon/demo_image:v3
        build:
          path: /home/azureuser/ansible-docker/build
        source: build
        push: yes